### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by kujo888** [apoorvlathey/eth-explorers-extension#1]
Any plans for a Firefox version of this extension? 

Would be willing to commission it

**Comment by apoorvlathey** [comment]
To work with firefox, the code needs to be modified a bit.
I'll open up a new branch to support it.

**Comment by apoorvlathey** [comment]
It's live!
[https://github.com/apoorvlathey/eth-explorers-extension/tree/firefox](https://github.com/apoorvlathey/eth-explorers-extension/tree/firefox)
